import type { NextPage } from 'next'
import Head from 'next/head'
import { Provider } from 'react-redux'
import store from '../components/redux/store'
import MyApp from '../components/app/MyApp'

const Home: NextPage = () => {

  return (
    <div>

      <Head>

        <title>Create Next App</title>

        <meta name="description" content="Generated by create next app" />

        <link rel="icon" href="/favicon.ico" />

      </Head>
      
      <Provider store={store}>
        
        <MyApp />
        
      </Provider>

    </div>
  )
}

export default Home
